[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Deaktiviere Caching für Prisma
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.prisma",
      ".next/cache"
    ]
